### PR TITLE
Add the packaging metadata to build the ghb0t snap

### PR DESCRIPTION
**Pull request by come-maiz**
This is a package for the secure installation of apps that works in most Linux distributions.
Landing it upstream will enable builds that then can be distributed to many users through the Ubuntu store.

### CODE REVIEW

**Comment by jessfraz** [comment]
Oh cool!!!

**Comment by come-maiz** [comment]
Hello @jessfraz!

After manually deleting like 50 branches, I thought there might be some better way to do it. And I found yours :)

I'm right now using it, and I also used it to test our latest snapcraft release, so I'm sending it upstream waiting to hear your honest feedback. That would be great for us. You can read more about snapcraft in https://snapcraft.io/

To give it a try in an Ubuntu 16.04:

    $ sudo apt install snapcraft git
    $ git clone https://github.com/elopio/ghb0t
    $ cd ghb0t
    $ snapcraft
    $ sudo snap install *.snap --dangerous

(dangerous because the snap you build doesn't come from the trusted store. After you push it to the ubuntu store, your users just have to run $ sudo snap install ghb0t

If you have any questions, please let me know.

**Comment by jessfraz** [comment]
Super cool!

**Comment by come-maiz** [comment]
oh, you didn't let me finish. Well, thank you very much for merging it. And also thanks, because it was magically deleted by the bot :blush: 

still eager for some feedback...

pura vida.

**Comment by jessfraz** [comment]
I've been meaning to play with snap so now I have even more reason too :)

**Comment by popey** [comment]
Now this is landed, can we get it uploaded to the store so everyone gets to benefit please :D
https://snapcraft.io/docs/build-snaps/ci-integration / https://snapcraft.io/docs/build-snaps/publish

**Pull request merged**
